# Uncomment this line to define a global platform for your project
#platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'RentApp' do
pod 'Google/SignIn'
end

target 'RentAppTests' do

end

target 'RentAppUITests' do

end

